/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.game;

import com.tankWar.server.LobbyServer;
import org.junit.Test;

import java.net.UnknownHostException;

public class AppTest {
    @Test public void appHasAGreeting() throws UnknownHostException {
        LobbyServer server=new LobbyServer();
    }
}
