/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.game;

import com.tankWar.lobby.ChatServer;
import com.tankWar.lobby.Client;
import org.junit.Test;

import java.net.InetAddress;
import java.net.UnknownHostException;

public class AppTest {
    @Test public void appHasAGreeting() throws UnknownHostException {
        ChatServer server=new ChatServer(InetAddress.getLocalHost());
    }
}
