/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.game;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;

public class App extends Application {
    public String getGreeting() {
        return "Hello World!";
    }

    @Override
    public void start(Stage primaryStage) {
        Label label = new Label("hello world!");

        Scene scene = new Scene(label, 400, 300);

        primaryStage.setScene(scene);
        primaryStage.setTitle("Hello");
        primaryStage.show();
    }

    public static void main(String[] args) {
        Application.launch(args);
//        System.out.println(new App().getGreeting());
    }
}
